name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    if: ${{ !contains(github.event.head_commit.message, 'Prepare for release') }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Gradlew permissions
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew check
